APP_NAME=SchoolMangementSystemERP
APP_ENV=local
APP_KEY=base64:b8/2+AmqZHc8DfzwDdYacxW6bdwUlXulcc7FlgpULJ0=
APP_DEBUG=true
APP_URL=http://demo.lyceumgroupofschools.com/

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=admin_schoolErp
DB_USERNAME=admin_schoolErp
DB_PASSWORD=lv2dadalyceum

DB_CONNECTION_SECOND=mysql
DB_HOST_SECOND=127.0.0.1
DB_PORT_SECOND=3306
DB_DATABASE_SECOND=admin_superior
DB_USERNAME_SECOND=admin_superior
DB_PASSWORD_SECOND=lv2dadalyceum

DB_CONNECTION_THIRD=mysql
DB_HOST_THIRD=127.0.0.1
DB_PORT_THIRD=3306
DB_DATABASE_THIRD=admin_slms
DB_USERNAME_THIRD=admin_slms
DB_PASSWORD_THIRD=lv2dadalyceum


BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379



PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
